config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  root 'home#index'

  resources :products do
    post :import,            on: :collection
    post :import_from_other, on: :collection
    post :all_stocks,        on: :member
    get :close,              on: :collection
  end

  resources :tickets, only: :create

  resources :inquiries, only: [:index, :create]

  resources :members, only: :index

  resources :timecards do
    get :start_working,  on: :member
    get :finish_working, on: :member
    get :close,          on: :member
  end

  resources :blogs do
    get :close, on: :collection
  end

  resources :reviews, only: [:create, :destroy]

  resources :sales, only: [:index, :create]

  resources :notice, only: :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :unit
  belongs_to :user

  validates :unit_id, presence: true
  validates :url,     presence: true

  default_scope -> { order(created_at: :desc) }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
  validates :staff_id, :route, :products, :conditions, :results, presence: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :sale
  belongs_to :user
  belongs_to :unit

  validates :price, presence: true
  validates :payment, presence: true
  validates :customer, presence: true

  default_scope -> { order(created_at: :desc) }

  def payment_by
    case self.payment
    when 0 then
      return "現金"
    when 1 then
      return "代引き"
    when 2 then
      return "クレカ"
    when 3 then
      return "QRコード"
    else
      return "未登録"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  has_many :timecards

  validates :name, presence: true
  validates :user_id, presence: true

  default_scope -> { order(created_at: :asc) }

  def working_start
    self.update_attributes( working: true)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user


  CSV_ATTRIBUTES = ['stock_id', 'name', 'color', 'category', 'cost', 'group_num', 'user_id', 'stocks']

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << CSV_ATTRIBUTES
      all.each do |product|
        csv << CSV_ATTRIBUTES.map{|attr| product.send(attr)}
      end
    end
  end

  def self.import(file, user_id)
    CSV.foreach(file.path, headers: true) do |row|
      product = Product.find_or_initialize_by(stock_id: row['stock_id'], user_id: user_id)
      product.update_attributes(stocks: row['stocks'])
      product.save!
    end
  end

  def self.import_from_other(file, user_id)
    CSV.foreach(file.path, headers: true) do |row|
      product = Product.find_or_initialize_by(stock_id: row[1], user_id: user_id)
      product.update_attributes(stock_id: row[1], name: row[2], color: row[3], category: row[5],
                                cost: row[6], group_num: row[9], stocks: row[11], user_id: user_id)
      product.save!
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user

  has_many :invoices
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :product_num, presence: true
  validates :user_num, presence: true
  validates :type_num, presence: true
  validates :count, presence: true

  def change_product_stocks(ticket, user_from_num)
    if ticket.type_num == 0..2
      product = Product.find_by(stock_id: ticket.product_num, user_id: ticket.user_num)
      product.update_attributes(stocks: product.stocks - ticket.count)
    elsif ticket.type_num == 3
      product1 = Product.find_by(stock_id: ticket.product_num, user_id: user_from_num.to_i)
      product1.update_attributes(stocks: product1.stocks - ticket.count)
      product2 = Product.find_by(stock_id: ticket.product_num, user_id: ticket.user_num)
      product2.update_attributes(stocks: product2.stocks + ticket.count)
    end
  end
end

app/models/timecard.rb
class Timecard < ApplicationRecord
  belongs_to :member

  validates :member_id, presence: true
  validates :start_time, presence: true

  default_scope -> { order(start_time: :asc) }
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :invoices
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :products
  has_many :inquiries
  has_many :members
  has_many :blogs
  has_many :reviews
  has_many :sales
  has_many :invoices

  def review_count_this_month
    this_month = Time.current.all_month
    Review.where( created_at: this_month, user_id: self.id ).count
  end

  def User.user_names_without_own(current_user)
    user_names_without_own = User.where.not(id: current_user.id).map(&:name).to_a
    user_names_without_own.length.times do |index|
      user_names_without_own[index] = [user_names_without_own[index], User.find_by(name: user_names_without_own[index]).id]
    end
    user_names_without_own
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    gon.data = []
    Unit.all.count.times do |index|
      next if index.zero?
      gon.data << Blog.where(unit_id: index, created_at: Time.current.beginning_of_month..Time.current.end_of_month).count
    end
    @blogs = current_user.blogs
  end

  def new
    @user = current_user
  end

  def close
    @user = current_user
  end

  def create
    blog = Blog.new(blog_params)
    if blog.save
      flash.notice = 'ブログ投稿数を１つ増やしました'
      redirect_to root_path
    else
      flash.alert = '入力が不適切です'
      redirect_to root_path
    end
  end

  def destroy
    Blog.find(params[:id]).destroy
    flash.notice = 'ブログを１件　削除しました'
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:unit_id, :url, :user_id)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def user_names_without_own
    User.user_names_without_own(current_user)
  end

  def a_route
    [["（必須）経路を選んで下さい", nil], "来店", "電話", "メール"]
  end

  def unit_names
    [["（必須）機種を選んでください", nil], ["iPhone", 1], ["Xperia", 2], ["Galaxy", 3], ["Zenfone", 4], ["ゲーム機", 5], ["Surface", 6], ["その他", 7]]
  end

  def staffs
    staffs  = [["（必須）スタッフを選んでください", nil]]
    members = Member.where(user_id: current_user.id)
    members.each_with_index do |member, index|
      staffs << [ member.name, member.id ]
    end
    staffs
  end

  def conditions
    [["（必須）症状を選んで下さい", nil], ["画面割れ", 1], ["バッテリー不良", 2],
     ["充電不良", 3], ["起動不良", 4], ["水没", 5],
     ["マイク不良", 6], ["スピーカー不良", 7], ["カメラ不良", 8], ["カメラレンズ割れ", 9],
     ["データ誤消去", 10], ["その他", 11]]
  end

  def results
    [["（必須）結果を選んでください", nil], ["受注", 1], ["来店予約", 2],
     ["料金や時間の確認", 3], ["失注：料金", 4], ["失注：時間", 5],
     ["失注：店舗在庫なし", 6], ["失注：取り扱いなし", 7],
     ["失注：修理できない", 8], ["失注：他にあてがある", 9]]
  end

  def current_time
    t = Time.current
    "#{t.month}月#{t.day}日　#{t.hour}時#{t.min}分"
  end

  def current_time_m_d
    t = Time.current
    "#{t.month}月#{t.day}日"
  end

  def payment
    [['現金', 0], ['代引き', 1], ['クレカ', 2], ['QRコード', 3]]
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timecards_helper.rb
module TimecardsHelper
  def total_worked_time(member)
    time_cards = member.timecards.where(created_at: Time.current.beginning_of_month..Time.current.end_of_month)
    total_time = { sec: 0 }
    time_cards.each do |t_card|
      total_time[:sec] += (t_card.end_time - t_card.start_time) unless t_card.end_time.nil?
    end
    total_time[:min]  = ((total_time[:sec] / 60) % 60).ceil
    total_time[:hour] = (total_time[:sec] / 3600).to_i
    total_time
  end
end

app/views/blogs/_blog_modal.html.erb
<div class="row">
  <div class="blog-box-modal col-12 p-5">
    <div class="h4 mb-4">以下の内容で記録</div>
    <%= form_for(user.blogs.build, url: blogs_path, method: :post) do |f| %>
      <%= f.hidden_field :user_id, value: user.id %>

      <%= f.select :unit_id, unit_names, {}, {selected: :first, class: "custom-select d-block w-100"} %>

      <%= f.text_field :url, class: "form-control my-3", placeholder: "ブログのURLをここに貼り付ける" %>

      <%= f.submit "追加", class: "btn btn-primary btn-block mt-4 mb-3" %>
    <% end %>
    <%= link_to '戻る', close_blogs_path, class: 'btn btn-outline-secondary w-100', remote: true %>
  </div>
</div>

app/views/blogs/_blog_td.html.erb
<tr>
  <td><%= blog.unit.name %></td>
  <td><%= blog.user.name %></td>
  <td><%= blog.created_at.strftime('%Y-%m-%d %H:%M') %></td>
  <td><%= link_to '', blog.url, class: 'fas fa-link dark' %></td>
  <td><%= link_to '', blog_path(blog), method: :delete, class: 'far fa-trash-alt dark text-muted', data: { confirm: '削除してよろしいですか？' } %></td>
</tr>

app/views/blogs/_side_menus.html.erb
<div class="col-12 side-box mt-5">
  <div class="row justify-content-around">
    <a class="col-4 side-menus non_selected" data-turbolinks="false" href=<%= root_path %>>
      <i class="fas fa-home h1 mt-3"></i>
      <span>Home</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= products_path %>>
      <i class="fas fa-cubes h1 mt-3"></i>
      <span>Products</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= inquiries_path %>>
      <i class="fas fa-file-contract h1 mt-3"></i>
      <span>Inquiry</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= sales_path %>>
      <i class="fas fa-money-check-alt h1 mt-3"></i>
      <span>Sales</span>
    </a>

    <a class="col-4 side-menus selected-menu" href=<%= blogs_path %>>
      <i class="fas fa-blog h1 mt-3"></i>
      <span>Blogs</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= timecards_path %>>
      <i class="fas fa-clock h1 mt-3"></i>
      <span>TimeCard</span>
    </a>
  </div>
</div>

app/views/blogs/close.js.erb
$("#blog-modal").hide();

app/views/blogs/index.html.erb
<div class="row">
  <div class="col-3">
    <div class="row justify-content-center">
      <%= render 'home/user_area' %>
      <%= render 'blogs/side_menus' %>
      <%= render 'home/changeable' %>
    </div>
  </div>
  <div class="col-9">
    <div class="row">
      <div class="col-11 blog-top rounded my-3 p-5">
        <div>全店トータル</div>
        <canvas id="myChart" width="200px" height="100px"></canvas>
        <script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['iPhone', 'Xepria', 'Galaxy', 'Zenfone', 'ゲーム機', 'Surface', 'その他'],
                    datasets: [{
                        label: '機種別ブログ投稿数',
                        data: gon.data,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)',
                            'rgba(127,127,138,0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)',
                            'rgba(127,127,138,1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                min: 0,
                                max: 10
                            }
                        }]
                    }
                }
            });
        </script>
      </div>
      <div class="col-11 blog-content rounded">
        <table class="table text-center">
          <thead>
            <tr>
              <th>機種</th>
              <th>投稿店舗</th>
              <th>投稿日時</th>
              <th>ブログURL</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: 'blogs/blog_td', collection: @blogs, as: :blog %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/blogs/new.js.erb
$("#blog-modal").html("<%= escape_javascript(render 'blogs/blog_modal', user: @user) %>").fadeIn();