config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  root 'home#index'

  resources :products do
    post :import,            on: :collection
    post :import_from_other, on: :collection
    post :all_stocks,        on: :member
    get :close,              on: :collection
  end

  resources :tickets, only: :create

  resources :inquiries, only: [:index, :create]

  resources :members, only: :index

  resources :timecards do
    get :start_working,  on: :member
    get :finish_working, on: :member
    get :close,          on: :member
  end

  resources :blogs do
    get :close, on: :collection
  end

  resources :reviews, only: [:create, :destroy]

  resources :sales, only: [:index, :create]

  resources :notice, only: :new
end

app/models/timecard.rb
class Timecard < ApplicationRecord
  belongs_to :member

  validates :member_id, presence: true
  validates :start_time, presence: true

  default_scope -> { order(start_time: :asc) }
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  before_action  :authenticate_user!

  def index
    @members = Member.where(user_id: current_user.id)
  end

  def show
    @time_card = Timecard.find(params[:id])
  end

  def update
    @time_card = Timecard.find(params[:id])
    if @time_card.update_attributes(timecard_params)
      flash.notice = 'タイムカードを正常に更新しました'
      redirect_to timecards_path
    else
      render 'index'
    end
  end

  def close
    @time_card = Timecard.find(params[:id])
  end

  def destroy
    Timecard.find(params[:id]).destroy
    flash.notice = 'タイムカードを１件削除しました'
    redirect_to timecards_path
  end

  def start_working
    @member = Member.find(params[:id])
    @member.timecards.create(start_time: Time.current, date_int: Time.current.day.to_i)
    @member.update_attributes( working: true)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def finish_working
    @member   = Member.find(params[:id])
    time_card = Timecard.find_by(member_id: @member.id, end_time: nil)
    time_card.update_attributes(end_time: Time.current)
    @member.update_attributes( working: false)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

  def timecard_params
    params.require(:timecard).permit(:start_time, :end_time)
  end
end

app/helpers/timecards_helper.rb
module TimecardsHelper
  def total_worked_time(member)
    time_cards = member.timecards.where(created_at: Time.current.beginning_of_month..Time.current.end_of_month)
    total_time = { sec: 0 }
    time_cards.each do |t_card|
      total_time[:sec] += (t_card.end_time - t_card.start_time) unless t_card.end_time.nil?
    end
    total_time[:min]  = ((total_time[:sec] / 60) % 60).ceil
    total_time[:hour] = (total_time[:sec] / 3600).to_i
    total_time
  end
end

app/views/timecards/_active_member.html.erb
<%= image_tag "/images/#{member.icon}", class: "icon-member rounded-circle my-3 active-icon"%>
<h6><%= member.name %></h6>
<div class="h4 mt-3">勤務中</div>
<div class="my-4 member-card-bottom">
  <%= link_to '退勤', finish_working_timecard_path(member.id),
              class: 'btn btn-sm btn-danger w-75',
              data: { confirm: "#{current_time}　退勤しますか？" },
              remote: true
  %>
</div>
<div class="active-circle rounded-circle"></div>

app/views/timecards/_no_active_member.html.erb
<%= image_tag "/images/#{member.icon}", class: "icon-member rounded-circle my-3 opacity-05"%>
<h6 class="opacity-05"><%= member.name %></h6>
<div class="h4 mt-3 text-muted">休み</div>
<div class="my-4 member-card-bottom">
  <%= link_to '出勤', start_working_timecard_path(member.id),
              class: 'btn btn-sm btn-info w-75',
              data: { confirm: "#{current_time}　出勤しますか？" },
              remote: true
  %>
</div>

app/views/timecards/_side_menus.html.erb
<div class="col-12 side-box mt-5">
  <div class="row justify-content-around">
    <a class="col-4 side-menus non_selected" data-turbolinks="false" href=<%= root_path %>>
      <i class="fas fa-home h1 mt-3"></i>
      <span>Home</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= products_path %>>
      <i class="fas fa-cubes h1 mt-3"></i>
      <span>Products</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= inquiries_path %>>
      <i class="fas fa-file-contract h1 mt-3"></i>
      <span>Inquiry</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= sales_path %>>
      <i class="fas fa-money-check-alt h1 mt-3"></i>
      <span>Sales</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= blogs_path %>>
      <i class="fas fa-blog h1 mt-3"></i>
      <span>Blogs</span>
    </a>

    <a class="col-4 side-menus selected-menu" href=<%= timecards_path %>>
      <i class="fas fa-clock h1 mt-3"></i>
      <span>TimeCard</span>
    </a>
  </div>
</div>

app/views/timecards/_time_card_modal.html.erb
<% unless t_card.nil? %>
  <div class="row">
    <div class="col time-card-box-modal px-5 py-3 text-center">
      <div class="row">
        <div class="col-12 p-3 h4">
          <%= t_card.member.name %>
        </div>
      </div>
      <%= form_for(t_card, url: timecard_path(t_card), method: :patch) do |f| %>
        <table class="table">
          <tbody>
            <tr>
              <th>始業</th>
              <td>
                <div class="form-group">
                  <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <%= f.text_field :start_time, class: "form-control datetimepicker-input", data: {target: "#datetimepicker1"}, value: "#{t_card.start_time.strftime('%Y-%m-%d %H:%M')}" %>
                    <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar-alt"></i></div>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <th>終業</th>
              <td>
                <div class="form-group">
                  <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                    <%= f.text_field :end_time, class: "form-control datetimepicker-input", data: {target: "#datetimepicker2"}, value: "#{t_card.end_time.strftime('%Y-%m-%d %H:%M')}" %>
                    <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar-alt"></i></div>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="row justify-content-center my-3">
          <%= link_to '戻る', close_timecard_path(t_card), class: 'col-2 mx-2 btn btn-outline-secondary', remote: true %>
          <%= f.submit "更新", class: "col-2 mx-2 btn btn btn-primary btn-block w-25" %>
          <%= link_to '削除', timecard_path(t_card), method: :delete, class: 'col-2 mx-2 btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/timecards/_work_time_list.html.erb
<div class="col-5 time-card-box p-3 my-2 mx-2">
  <div class="row text-center">
    <div class="col-4">
      <%= image_tag "/images/#{member.icon}", class: "icon-member rounded-circle my-3 active-icon"%>
    </div>
    <div class="col-8">
      <h5><%= member.name %></h5>
      <div class="h6 mt-3">
        出勤数　<%= member.timecards
                 .where(start_time: Time.current.beginning_of_month..Time.current.end_of_month)
                 .select(:start_time)
                 .distinct
                 .count %>
      </div>
      <div class="h6">
        総時間　<%= total_worked_time(member)[:hour] %>時間 <%= total_worked_time(member)[:min] %>分
      </div>
    </div>
    <div class="col-12 ">
      <table class="table">
        <thead>
          <tr>
            <th>日付</th>
            <th>始業</th>
            <th>終業</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% member.timecards.each do |t_card| %>
            <tr>
              <td><%= t_card.start_time.strftime('%d') %>日</td>
              <td><%= t_card.start_time.nil? ? "---" : "#{t_card.start_time.strftime('%H:%M')}" %></td>
              <td><%= t_card.end_time.nil? ? "---" : "#{t_card.end_time.strftime('%H:%M')}" %></td>
              <td><%= link_to '', timecard_path(t_card.id), class: 'far fa-edit text-muted', remote: true %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/timecards/close.js.erb
$("#time_card_modal").html("<%= escape_javascript(render 'time_card_modal', t_card: @time_card) %>").hide();

app/views/timecards/finish_working.js.erb
$("#member-<%= @member.id.to_s %>").html("<%= escape_javascript(render('timecards/no_active_member', member: @member)) %>");

app/views/timecards/index.html.erb
<div class="row">
  <div class="col-3">
    <div class="row justify-content-center">
      <%= render 'home/user_area' %>
      <%= render 'timecards/side_menus' %>
      <%= render 'home/changeable' %>
    </div>
  </div>
  <div class="col-9">
    <div class="row ml-4">
      <div class="col-12">
        <h4 class="text-white">店舗内スタッフ　勤怠記録</h4>
      </div>
      <div class="col-12">
        <div class="row">
          <%= render partial: 'timecards/work_time_list', collection: @members, as: :member %>
        </div>
      </div>
      <div class="col-12 mt-4">
        <div class="row">
          <%= render partial: 'home/member_card', collection: @members, as: :member %>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="time_card_modal" class="time_card_modal">
  <%= render 'time_card_modal', t_card: @members.first.timecards.second %>
</div>

app/views/timecards/show.js.erb
$("#time_card_modal").html("<%= escape_javascript(render 'time_card_modal', t_card: @time_card) %>").fadeIn();
//$(".time-card-box-modal").addClass('time-fade-in');

app/views/timecards/start_working.js.erb
$("#member-<%= @member.id.to_s %>").html("<%= escape_javascript(render('timecards/active_member', member: @member)) %>");