config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  root 'home#index'

  resources :products do
    post :import,            on: :collection
    post :import_from_other, on: :collection
    post :all_stocks,        on: :member
    get :close,              on: :collection
  end

  resources :tickets, only: :create

  resources :inquiries, only: [:index, :create]

  resources :members, only: :index

  resources :timecards do
    get :start_working,  on: :member
    get :finish_working, on: :member
    get :close,          on: :member
  end

  resources :blogs do
    get :close, on: :collection
  end

  resources :reviews, only: [:create, :destroy]

  resources :sales, only: [:index, :create]

  resources :notice, only: :new
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :unit
  belongs_to :user

  validates :unit_id, presence: true
  validates :url,     presence: true

  default_scope -> { order(created_at: :desc) }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
  validates :staff_id, :route, :products, :conditions, :results, presence: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :sale
  belongs_to :user
  belongs_to :unit

  validates :price, presence: true
  validates :payment, presence: true
  validates :customer, presence: true

  default_scope -> { order(created_at: :desc) }

  def payment_by
    case self.payment
    when 0 then
      return "現金"
    when 1 then
      return "代引き"
    when 2 then
      return "クレカ"
    when 3 then
      return "QRコード"
    else
      return "未登録"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  has_many :timecards

  validates :name, presence: true
  validates :user_id, presence: true

  default_scope -> { order(created_at: :asc) }

  def working_start
    self.update_attributes( working: true)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user


  CSV_ATTRIBUTES = ['stock_id', 'name', 'color', 'category', 'cost', 'group_num', 'user_id', 'stocks']

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << CSV_ATTRIBUTES
      all.each do |product|
        csv << CSV_ATTRIBUTES.map{|attr| product.send(attr)}
      end
    end
  end

  def self.import(file, user_id)
    CSV.foreach(file.path, headers: true) do |row|
      product = Product.find_or_initialize_by(stock_id: row['stock_id'], user_id: user_id)
      product.update_attributes(stocks: row['stocks'])
      product.save!
    end
  end

  def self.import_from_other(file, user_id)
    CSV.foreach(file.path, headers: true) do |row|
      product = Product.find_or_initialize_by(stock_id: row[1], user_id: user_id)
      product.update_attributes(stock_id: row[1], name: row[2], color: row[3], category: row[5],
                                cost: row[6], group_num: row[9], stocks: row[11], user_id: user_id)
      product.save!
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user

  has_many :invoices
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :product_num, presence: true
  validates :user_num, presence: true
  validates :type_num, presence: true
  validates :count, presence: true

  def change_product_stocks(ticket, user_from_num)
    if ticket.type_num == 0..2
      product = Product.find_by(stock_id: ticket.product_num, user_id: ticket.user_num)
      product.update_attributes(stocks: product.stocks - ticket.count)
    elsif ticket.type_num == 3
      product1 = Product.find_by(stock_id: ticket.product_num, user_id: user_from_num.to_i)
      product1.update_attributes(stocks: product1.stocks - ticket.count)
      product2 = Product.find_by(stock_id: ticket.product_num, user_id: ticket.user_num)
      product2.update_attributes(stocks: product2.stocks + ticket.count)
    end
  end
end

app/models/timecard.rb
class Timecard < ApplicationRecord
  belongs_to :member

  validates :member_id, presence: true
  validates :start_time, presence: true

  default_scope -> { order(start_time: :asc) }
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :invoices
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :products
  has_many :inquiries
  has_many :members
  has_many :blogs
  has_many :reviews
  has_many :sales
  has_many :invoices

  def review_count_this_month
    this_month = Time.current.all_month
    Review.where( created_at: this_month, user_id: self.id ).count
  end

  def User.user_names_without_own(current_user)
    user_names_without_own = User.where.not(id: current_user.id).map(&:name).to_a
    user_names_without_own.length.times do |index|
      user_names_without_own[index] = [user_names_without_own[index], User.find_by(name: user_names_without_own[index]).id]
    end
    user_names_without_own
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action  :authenticate_user!, only: :index

  def index
    @user     = current_user
    set_sales_data
    set_blog_data
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def user_names_without_own
    User.user_names_without_own(current_user)
  end

  def a_route
    [["（必須）経路を選んで下さい", nil], "来店", "電話", "メール"]
  end

  def unit_names
    [["（必須）機種を選んでください", nil], ["iPhone", 1], ["Xperia", 2], ["Galaxy", 3], ["Zenfone", 4], ["ゲーム機", 5], ["Surface", 6], ["その他", 7]]
  end

  def staffs
    staffs  = [["（必須）スタッフを選んでください", nil]]
    members = Member.where(user_id: current_user.id)
    members.each_with_index do |member, index|
      staffs << [ member.name, member.id ]
    end
    staffs
  end

  def conditions
    [["（必須）症状を選んで下さい", nil], ["画面割れ", 1], ["バッテリー不良", 2],
     ["充電不良", 3], ["起動不良", 4], ["水没", 5],
     ["マイク不良", 6], ["スピーカー不良", 7], ["カメラ不良", 8], ["カメラレンズ割れ", 9],
     ["データ誤消去", 10], ["その他", 11]]
  end

  def results
    [["（必須）結果を選んでください", nil], ["受注", 1], ["来店予約", 2],
     ["料金や時間の確認", 3], ["失注：料金", 4], ["失注：時間", 5],
     ["失注：店舗在庫なし", 6], ["失注：取り扱いなし", 7],
     ["失注：修理できない", 8], ["失注：他にあてがある", 9]]
  end

  def current_time
    t = Time.current
    "#{t.month}月#{t.day}日　#{t.hour}時#{t.min}分"
  end

  def current_time_m_d
    t = Time.current
    "#{t.month}月#{t.day}日"
  end

  def payment
    [['現金', 0], ['代引き', 1], ['クレカ', 2], ['QRコード', 3]]
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timecards_helper.rb
module TimecardsHelper
  def total_worked_time(member)
    time_cards = member.timecards.where(created_at: Time.current.beginning_of_month..Time.current.end_of_month)
    total_time = { sec: 0 }
    time_cards.each do |t_card|
      total_time[:sec] += (t_card.end_time - t_card.start_time) unless t_card.end_time.nil?
    end
    total_time[:min]  = ((total_time[:sec] / 60) % 60).ceil
    total_time[:hour] = (total_time[:sec] / 3600).to_i
    total_time
  end
end

app/views/home/_blogs_box.html.erb
<div class="col-6 blog-box text-center">
  <div class="row">
    <div class="col-12 h5 font-concert-one pt-3 pb-1 m-0">
      今月のブログ投稿数
    </div>
  </div>
  <canvas id="myChartDoughnut1" height="220px"></canvas>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <script>
      var ctx = document.getElementById('myChartDoughnut1').getContext('2d');
      var chart = new Chart(ctx, {
          // The type of chart we want to create
          type: 'pie',

          // The data for our dataset
          data: {
              labels: gon.unit_names,
              datasets: [{
                  backgroundColor: ['rgba(255,84,94,0.7)',
                      'rgba(103,255,77,0.7)',
                      'rgba(91,160,255,0.7)',
                      'rgba(234,106,255,0.7)',
                      'rgba(255,255,64,0.87)',
                      'rgb(36,226,144)',
                      'rgba(132,131,136,0.7)' ],
                  weight: 500,
                  data: gon.unit_each_blog
              }]
          },

          // Configuration options go here
          options: {}
      });
  </script>
  <%= link_to '', new_blog_path, class: 'col-2 offset-8 btn btn-sm btn-primary mt-2 fas fa-plus-circle', remote: true %>
</div>
<div class="blog-modal col" id="blog-modal">
  <%= render 'blogs/blog_modal', user: @user %>
</div>

app/views/home/_changeable.html.erb
<div class="col-11 changeable-box w-100 rounded m-2 text-white">
  <div class="row justify-content-center">
    <div class="col-8 changeable-box-top text-center my-4 py-1 h4 rounded">
      今月のお知らせ
    </div>
    <div class="col-12 text-center">
      ・お盆期間（10日〜18日）の<br>
      　配送について<br>
      　詳細はTalkNote要確認<br>
      <br>
      ・ブログ&レビュー投票期限<br>　
      　14日（金）<br>
      <br>
    </div>
  </div>
</div>

app/views/home/_inquiry_box.html.erb
<div class="h5">問合せ入力シート</div>
<div class="h1 py-2 display-3 text-center inquiry-logo">
  <i class="fas fa-info-circle"></i>
</div>
<%= form_for(user.inquiries.build, method: :post) do |f| %>
  <div class="h6 py-2 font-weight-normal letter-s text-muted">電話など、お客様から問い合わせを受けた時に記録として入力します</div>

  <div class="form-group staff-select">
    <%= f.select :staff_id, staffs, {}, {selected: :first, class: "custom-select d-block w-100"} %>
  </div>

  <div class="form-group route-select">
    <%= f.select :route, a_route, {}, {selected: :first, class: "custom-select d-block w-100"} %>
  </div>

  <div class="form-group unit-select">
    <%= f.select :products, unit_names, {}, {selected: :first, class: "custom-select d-block w-100"} %>
  </div>

  <%= f.text_field :series, class: "form-control my-3", id: "series-field", placeholder: "シリーズ、型番などを入力" %>

  <div class="form-group condition-select">
    <%= f.select :conditions, conditions, {}, {selected: :first, class: "custom-select d-block w-100"} %>
  </div>

  <%= f.text_field :memo, class: "form-control my-3", id: "memo-field", placeholder: "備考：上記に当てはまらない症状など" %>

  <div class="form-group result-select">
    <%= f.select :results, results, {}, {selected: :first, class: "custom-select d-block w-100"} %>
  </div>
  <%= f.hidden_field :user_id, value: user.id %>
  <%= f.submit "記録", class: "btn btn-lg btn-info btn-block mt-4" %>
<% end %>

app/views/home/_member_card.html.erb
<div class="col-2 mx-3 mb-4 member-cards text-center" id="member-<%= member.id %>">
  <% if member.working %>
    <%= render 'timecards/active_member', member: member %>
  <% else %>
    <%= render 'timecards/no_active_member', member: member %>
  <% end %>
</div>

app/views/home/_review_box.html.erb
<div class="col-5 review-box">
  <div class="row">
    <div class="col-12 h5 font-concert-one p-3 mt-2 text-center">
      Googleレビュー獲得数
    </div>
  </div>
  <div class="col-12 mt-2">
    <div class="rotating progress" id="progress2"></div>
    <script>
        window.onload = function onLoad() {
            var circle = new ProgressBar.Circle('#progress2', {
                color: '#ffab2c',
                trailColor: '#d4d4d4',
                strokeWidth: 10,
                duration: 1000,
                easing: 'easeInOut'
            });

            circle.set(0.05);

            setTimeout(function() {
                circle.animate(1);
            }, 0);
        };
    </script>
    <span class="col-12 review-counts font-concert-one text-center">
      <%= @user.review_count_this_month %>
    </span>
  </div>
  <%= link_to '', reviews_path,
              method: :post,
              class: 'col-2 offset-8 btn btn-sm btn-primary mt-4 fas fa-plus-circle',
              data: { confirm: 'レビューを１件追加しますか？' } %>
</div>

app/views/home/_side_menus.html.erb
<div class="col-12 side-box mt-5">
  <div class="row justify-content-around">
    <a class="col-4 side-menus selected-menu" data-turbolinks="false" href=<%= root_path %>>
      <i class="fas fa-home h1 mt-3"></i>
      <span>Home</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= products_path %>>
      <i class="fas fa-cubes h1 mt-3"></i>
      <span>Products</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= inquiries_path %>>
      <i class="fas fa-file-contract h1 mt-3"></i>
      <span>Inquiry</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= sales_path %>>
      <i class="fas fa-money-check-alt h1 mt-3"></i>
      <span>Sales</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= blogs_path %>>
      <i class="fas fa-blog h1 mt-3"></i>
      <span>Blogs</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= timecards_path %>>
      <i class="fas fa-clock h1 mt-3"></i>
      <span>TimeCard</span>
    </a>
  </div>
</div>

app/views/home/_user_area.html.erb
<div class="col-12 user-area text-center">
  <%= image_tag "/images/#{current_user.image}", class: "user-image rounded-circle my-3"%>
  <div class="h2"><%= current_user.name %></div>
  <p>Tel: <%= current_user.tel %></p>
  <p><%= current_user.address %></p>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-3">
    <div class="row justify-content-center">
      <%= render 'home/user_area' %>
      <%= render 'home/side_menus' %>
      <%= render 'home/changeable' %>
    </div>
  </div>
  <div class="col-9">
    <div class="row">
      <div class="col-12 p-2 px-4">
        <div class="row">
          <div class="text-white h4 col-4"><%= Time.current.strftime('%Y年 %m月 %d日') %></div>
        </div>
      </div>
      <div class="col-8">
        <div class="row px-3">
          <div class="col-12 sales-box mb-4 py-3">
            <div class="h5">売り上げ推移</div>
            <%= render 'sales/chart_graph' %>
          </div>
          <div class="col-12">
            <div class="row justify-content-between">
              <%= render 'home/blogs_box' %>
              <%= render 'home/review_box' %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-4 inquiry-box pt-3">
        <%= render 'home/inquiry_box', user: @user %>
      </div>
      <div class="col-12 mt-4">
        <div class="row">
          <%= render partial: 'home/member_card', collection: @user.members, as: :member %>
        </div>
      </div>
    </div>
  </div>
</div>