config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  root 'home#index'

  resources :products do
    post :import,            on: :collection
    post :import_from_other, on: :collection
    post :all_stocks,        on: :member
    get :close,              on: :collection
  end

  resources :tickets, only: :create

  resources :inquiries, only: [:index, :create]

  resources :members, only: :index

  resources :timecards do
    get :start_working,  on: :member
    get :finish_working, on: :member
    get :close,          on: :member
  end

  resources :blogs do
    get :close, on: :collection
  end

  resources :reviews, only: [:create, :destroy]

  resources :sales, only: [:index, :create]

  resources :notice, only: :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :unit
  belongs_to :user

  validates :unit_id, presence: true
  validates :url,     presence: true

  default_scope -> { order(created_at: :desc) }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
  validates :staff_id, :route, :products, :conditions, :results, presence: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :sale
  belongs_to :user
  belongs_to :unit

  validates :price, presence: true
  validates :payment, presence: true
  validates :customer, presence: true

  default_scope -> { order(created_at: :desc) }

  def payment_by
    case self.payment
    when 0 then
      return "現金"
    when 1 then
      return "代引き"
    when 2 then
      return "クレカ"
    when 3 then
      return "QRコード"
    else
      return "未登録"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  has_many :timecards

  validates :name, presence: true
  validates :user_id, presence: true

  default_scope -> { order(created_at: :asc) }

  def working_start
    self.update_attributes( working: true)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user


  CSV_ATTRIBUTES = ['stock_id', 'name', 'color', 'category', 'cost', 'group_num', 'user_id', 'stocks']

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << CSV_ATTRIBUTES
      all.each do |product|
        csv << CSV_ATTRIBUTES.map{|attr| product.send(attr)}
      end
    end
  end

  def self.import(file, user_id)
    CSV.foreach(file.path, headers: true) do |row|
      product = Product.find_or_initialize_by(stock_id: row['stock_id'], user_id: user_id)
      product.update_attributes(stocks: row['stocks'])
      product.save!
    end
  end

  def self.import_from_other(file, user_id)
    CSV.foreach(file.path, headers: true) do |row|
      product = Product.find_or_initialize_by(stock_id: row[1], user_id: user_id)
      product.update_attributes(stock_id: row[1], name: row[2], color: row[3], category: row[5],
                                cost: row[6], group_num: row[9], stocks: row[11], user_id: user_id)
      product.save!
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user

  has_many :invoices
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :product_num, presence: true
  validates :user_num, presence: true
  validates :type_num, presence: true
  validates :count, presence: true

  def change_product_stocks(ticket, user_from_num)
    if ticket.type_num == 0..2
      product = Product.find_by(stock_id: ticket.product_num, user_id: ticket.user_num)
      product.update_attributes(stocks: product.stocks - ticket.count)
    elsif ticket.type_num == 3
      product1 = Product.find_by(stock_id: ticket.product_num, user_id: user_from_num.to_i)
      product1.update_attributes(stocks: product1.stocks - ticket.count)
      product2 = Product.find_by(stock_id: ticket.product_num, user_id: ticket.user_num)
      product2.update_attributes(stocks: product2.stocks + ticket.count)
    end
  end
end

app/models/timecard.rb
class Timecard < ApplicationRecord
  belongs_to :member

  validates :member_id, presence: true
  validates :start_time, presence: true

  default_scope -> { order(start_time: :asc) }
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :invoices
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :products
  has_many :inquiries
  has_many :members
  has_many :blogs
  has_many :reviews
  has_many :sales
  has_many :invoices

  def review_count_this_month
    this_month = Time.current.all_month
    Review.where( created_at: this_month, user_id: self.id ).count
  end

  def User.user_names_without_own(current_user)
    user_names_without_own = User.where.not(id: current_user.id).map(&:name).to_a
    user_names_without_own.length.times do |index|
      user_names_without_own[index] = [user_names_without_own[index], User.find_by(name: user_names_without_own[index]).id]
    end
    user_names_without_own
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    params[:q]['name_cont_all'] = params[:q]['name_cont_all'].split(/[\p{blank}\s]+/) unless params[:q].nil?
    @q = current_user.products.ransack(params[:q])
    @products = @q.result(distinct: true)
    @ticket   = Ticket.new
    @product  = @products.first

    respond_to do |format|
      format.html
      format.csv { send_data @products.generate_csv, filename: "product-#{Time.current.strftime('%Y%m%d%H%M')}.csv" }
    end
  end

  def all_stocks
    @product  = Product.find(params[:id])
    @products = []
    User.count.times do |index|
      @products << ((p = Product.find_by(stock_id: @product.stock_id, user_id: index + 1)) ?
          [ p.user.name, p.stocks ] : [ User.find(index + 1).name, 0 ])
    end
  end

  def close

  end

  def import
    current_user.products.import(params[:file], current_user.id)
    redirect_to products_path, notice: '在庫データをインポートしました'
  end

  def import_from_other
    current_user.products.import_from_other(params[:file], current_user.id)
    redirect_to products_path, notice: '在庫データをインポートしました'
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def user_names_without_own
    User.user_names_without_own(current_user)
  end

  def a_route
    [["（必須）経路を選んで下さい", nil], "来店", "電話", "メール"]
  end

  def unit_names
    [["（必須）機種を選んでください", nil], ["iPhone", 1], ["Xperia", 2], ["Galaxy", 3], ["Zenfone", 4], ["ゲーム機", 5], ["Surface", 6], ["その他", 7]]
  end

  def staffs
    staffs  = [["（必須）スタッフを選んでください", nil]]
    members = Member.where(user_id: current_user.id)
    members.each_with_index do |member, index|
      staffs << [ member.name, member.id ]
    end
    staffs
  end

  def conditions
    [["（必須）症状を選んで下さい", nil], ["画面割れ", 1], ["バッテリー不良", 2],
     ["充電不良", 3], ["起動不良", 4], ["水没", 5],
     ["マイク不良", 6], ["スピーカー不良", 7], ["カメラ不良", 8], ["カメラレンズ割れ", 9],
     ["データ誤消去", 10], ["その他", 11]]
  end

  def results
    [["（必須）結果を選んでください", nil], ["受注", 1], ["来店予約", 2],
     ["料金や時間の確認", 3], ["失注：料金", 4], ["失注：時間", 5],
     ["失注：店舗在庫なし", 6], ["失注：取り扱いなし", 7],
     ["失注：修理できない", 8], ["失注：他にあてがある", 9]]
  end

  def current_time
    t = Time.current
    "#{t.month}月#{t.day}日　#{t.hour}時#{t.min}分"
  end

  def current_time_m_d
    t = Time.current
    "#{t.month}月#{t.day}日"
  end

  def payment
    [['現金', 0], ['代引き', 1], ['クレカ', 2], ['QRコード', 3]]
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timecards_helper.rb
module TimecardsHelper
  def total_worked_time(member)
    time_cards = member.timecards.where(created_at: Time.current.beginning_of_month..Time.current.end_of_month)
    total_time = { sec: 0 }
    time_cards.each do |t_card|
      total_time[:sec] += (t_card.end_time - t_card.start_time) unless t_card.end_time.nil?
    end
    total_time[:min]  = ((total_time[:sec] / 60) % 60).ceil
    total_time[:hour] = (total_time[:sec] / 3600).to_i
    total_time
  end
end

app/views/products/_defective_product.html.erb
<div class="h5 p-2">初期不良</div>
<%= form_for(ticket, method: :post) do |f| %>
  <table class="table text-center">
    <thead>
    <tr>
      <th>在庫ID</th>
      <th>個数</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="text-center">
    <tr>
      <td>
        <%= f.number_field :product_num, class: "form-control d-block w-100" %>
      </td>
      <td>
        <%= f.number_field :count, class: "form-control d-block w-100", value: 1 %>
      </td>
      <%= f.hidden_field :user_num, value: current_user.id %>
      <%= f.hidden_field :type_num, value: 2 %>
      <td>
        <%= f.submit "登録", style: 'z-index: 10;',
                     data: { confirm: '初期不良に登録します。よろしいですか？' },
                     class: "btn btn-sm btn-warning btn-block mt-1 w-100 text-white"
        %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/products/_lost_product.html.erb
<div class="h5 p-2">ロスパーツ登録</div>
<%= form_for(ticket, method: :post) do |f| %>
  <table class="table text-center">
    <thead>
    <tr>
      <th>在庫ID</th>
      <th>個数</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="text-center">
    <tr>
      <td>
        <%= f.number_field :product_num, class: "form-control d-block w-100" %>
      </td>
      <td>
        <%= f.number_field :count, class: "form-control d-block w-100", value: 1 %>
      </td>
      <%= f.hidden_field :user_num, value: current_user.id %>
      <%= f.hidden_field :type_num, value: 1 %>
      <td>
        <%= f.submit "登録", style: 'z-index: 10;',
                     data: { confirm: 'ロス登録します。よろしいですか？' },
                     class: "btn btn-sm btn-danger btn-block mt-1 w-100 text-white"
        %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/products/_other_user_products.html.erb
<div class="h5 p-2">他店　取り寄せ</div>
<%= form_for(ticket, method: :post) do |f| %>
  <table class="table text-center">
    <thead>
    <tr>
      <th>取り寄せ先</th>
      <th>在庫ID</th>
      <th>個数</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="text-center">
    <tr>
      <td>
        <%= f.select :user_from_num, user_names_without_own, {}, {selected: :first, class: "custom-select d-block w-100"} %>
      </td>
      <td>
        <%= f.number_field :product_num, class: "form-control d-block w-100" %>
      </td>
      <td>
        <%= f.number_field :count, class: "form-control d-block w-100", value: 1 %>
      </td>
      <%= f.hidden_field :user_num, value: current_user.id %>
      <%= f.hidden_field :type_num, value: 3 %>
      <td>
        <%= f.submit "登録", style: 'z-index: 10;',
                     data: { confirm: '他店舗から取り寄せを登録します。よろしいですか？' },
                     class: "btn btn-sm btn-success btn-block mt-1 w-100"
        %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/products/_products_right_box.html.erb
<div class="row">
  <div class="col-12 h4 text-center text-white mt-5">
    <i class="fas fa-boxes"> 在庫一括処理（棚卸し）</i>
  </div>
  <div class="col-12 text-center p-5">
    <%= link_to 'CSV エクスポート', products_path(format: :csv), class: 'btn btn-info w-100' %>
    <%= form_tag import_products_path, multipart: true, class: 'mt-5' do %>
      <%= file_field_tag :file %>
      <%= submit_tag 'CSV インポート', class: 'btn btn-info w-100 mt-2' %>
    <% end %>

    <%= form_tag import_from_other_products_path, multipart: true, class: 'mt-5' do %>
      <%= file_field_tag :file %>
      <%= submit_tag 'CSV インポート(スマレジから)', class: 'btn btn-danger mt-2 w-100' %>
    <% end %>
  </div>
</div>

app/views/products/_products_td.html.erb
<tr>
  <td><%= product.stock_id %></td>
  <td><%= link_to product.name, all_stocks_product_path(product), method: :post, remote: true, class: 'text-black' %></td>
  <td><%= product.color %></td>
  <td>¥<%= product.cost.to_i %></td>
  <td><%= product.stocks %></td>
</tr>

app/views/products/_side_menus.html.erb
<div class="col-12 side-box mt-5">
  <div class="row justify-content-around">
    <a class="col-4 side-menus non_selected" data-turbolinks="false" href=<%= root_path %>>
      <i class="fas fa-home h1 mt-3"></i>
      <span>Home</span>
    </a>

    <a class="col-4 side-menus selected-menu" href=<%= products_path %>>
      <i class="fas fa-cubes h1 mt-3"></i>
      <span>Products</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= inquiries_path %>>
      <i class="fas fa-file-contract h1 mt-3"></i>
      <span>Inquiry</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= sales_path %>>
      <i class="fas fa-money-check-alt h1 mt-3"></i>
      <span>Sales</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= blogs_path %>>
      <i class="fas fa-blog h1 mt-3"></i>
      <span>Blogs</span>
    </a>

    <a class="col-4 side-menus non_selected" href=<%= timecards_path %>>
      <i class="fas fa-clock h1 mt-3"></i>
      <span>TimeCard</span>
    </a>
  </div>
</div>

app/views/products/_stocks_modal.html.erb
<div class="row">
  <div class="product-box-modal col-12 px-5 py-4">
    <div class="h5 mb-3 text-center"><%= @product.name unless @product.nil? %></div>
    <table class="table">
      <tbody class="w-50">
        <%= render partial: 'products/td_modal', collection: @products, as: :product %>
      </tbody>
    </table>
    <%= link_to '戻る', close_products_path, class: 'btn btn-outline-secondary w-100', remote: true %>
  </div>
</div>

app/views/products/_table_products.html.erb
<table class="table table-striped text-center">
  <thead>
  <tr>
    <th>在庫ID</th>
    <th>パーツ名</th>
    <th>色</th>
    <th>原価</th>
    <th>在庫</th>
  </tr>
  </thead>
  <tbody>
    <%= render partial: 'products/products_td', collection: products, as: :product %>
  </tbody>
</table>

app/views/products/_td_modal.html.erb
<tr>
  <td><%= product[0] %></td>
  <td><%= product[1] %></td>
</tr>

app/views/products/_used_product.html.erb
<div class="h5 p-2">使用パーツ登録</div>
<%= form_for(ticket, method: :post) do |f| %>
  <table class="table text-center">
    <thead>
    <tr>
      <th>在庫ID</th>
      <th>個数</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="text-center">
    <tr>
      <td>
        <%= f.number_field :product_num, class: "form-control d-block w-100" %>
      </td>
      <td>
        <%= f.number_field :count, class: "form-control d-block w-100", value: 1 %>
      </td>
      <%= f.hidden_field :user_num, value: current_user.id %>
      <%= f.hidden_field :type_num, value: 0 %>
      <td>
        <%= f.submit "登録", style: 'z-index: 10;',
                     data: { confirm: '使用済み登録します。よろしいですか？' },
                     class: "btn btn-sm btn-success btn-block mt-1 w-100"
        %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/products/all_stocks.js.erb
$("#product-modal").html("<%= escape_javascript(render 'products/stocks_modal') %>").fadeIn();

app/views/products/close.js.erb
$("#product-modal").hide();

app/views/products/index.html.erb
<div class="row">
  <div class="col-3">
    <div class="row justify-content-center">
      <%= render 'home/user_area' %>
      <%= render 'products/side_menus' %>
      <%= render 'home/changeable' %>
    </div>
  </div>
  <div class="col-9">
    <div class="row">
      <div class="col-11 rounded-top bg-white">
        <div class="pt-3 pb-1">
          <%= search_form_for @q, class: '' do |f| %>
            <div class="row form-group justify-content-center">
              <%= f.label :name_cont_all, 'パーツ名', class: 'col-2 col-form-label text-center' %>
              <div class="col-8">
                <%= f.search_field :name_cont_all, class: 'form-control' %>
              </div>
              <div class="col-2">
                <%= f.submit class: 'btn btn-outline-primary', value: '検索' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-11 product-content rounded-bottom">
        <%= render 'products/table_products', products: @products %>
      </div>
      <div class="col-11 mt-3">
        <div class="row">
          <div class="col-7">
            <div class="row">
              <div class="col-12 product-box rounded bg-white">
                <%= render 'products/used_product', ticket: @ticket %>
              </div>
              <div class="col-12 mt-2 product-box rounded bg-white">
                <%= render 'products/defective_product', ticket: @ticket %>
              </div>
              <div class="col-12 mt-2 product-box rounded bg-white">
                <%= render 'products/lost_product', ticket: @ticket %>
              </div>
            </div>
          </div>
          <div class="col-5">
            <div class="product-box-right rounded h-100">
              <%= render 'products/products_right_box' %>
            </div>
          </div>
          <div class="col-12 mt-3 product-box rounded bg-white">
            <%= render 'products/other_user_products', ticket: @ticket %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="product-modal col" id="product-modal">
  <%= render 'products/stocks_modal', product: @product %>
</div>